{{- if .Values.imagePullSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecret.secretName }}
{{- if .Values.imagePullSecret.annotations }}
  annotations:
{{ toYaml .Values.imagePullSecret.annotations | indent 4 }}
{{- end }}
{{- if .Values.imagePullSecret.labels }}
  labels:
{{ toYaml .Values.imagePullSecret.labels | indent 4 }}
{{- end }}
data:
{{- if .Values.addAuthField }}
  .dockerconfigjson: {{ include "imagepullsecrets.dockerconfigjson-with-auth" .Values.imagePullSecret | nospace | b64enc | quote }}
{{- else }}
  .dockerconfigjson: {{ include "imagepullsecrets.dockerconfigjson" .Values.imagePullSecret | nospace | b64enc | quote }}
{{- end }}
type: kubernetes.io/dockerconfigjson
{{- end }}
{{- end }}
